# Generated by Django 4.2.16 on 2024-12-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer_app', '0002_alter_topup_nominal_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(default='Menunggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='userb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='Menunggu', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
