# Generated by Django 4.2.16 on 2024-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0004_isipulsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='isipulsa',
            name='status',
            field=models.CharField(default='Menunggu', max_length=20),
        ),
    ]
