# Generated by Django 4.2.16 on 2024-12-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
