# Generated by Django 4.2.16 on 2024-12-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='literasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('deskripsi', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('link_literasi', models.CharField(default='default_link', max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_literasi')),
            ],
        ),
    ]
